version: '3'
services:
  # database
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    ports:
      - 27017:27017

  # gateway
  fnapigw:
    image: fnapigw:latest
    container_name: fn_api_gw
    restart: always
    ports: 
      - 8080:8080
    depends_on:
      - mongodb